-- AI-generated intro blurb shown on the social profile (under Locations).
-- Generated by the owner (via the profile-summary serverless function) and
-- cached here so every viewer reads the same text without re-calling OpenAI.
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS ai_summary            text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS ai_summary_updated_at timestamptz;
